import { createFileRoute } from "@tanstack/react-router";
import { DashboardLayout } from "@/components/dashboard/DashboardLayout";
import { Kpi, Note, Section, DataTable, PctBar, EmptyState } from "@/components/dashboard/widgets";
import { areaRevenue, fmtNaira, growth, achievement, headlineRevenue } from "@/data/itf2024";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Legend, CartesianGrid, PieChart, Pie, Cell } from "recharts";
import { useYear } from "@/lib/year-context";

export const Route = createFileRoute("/revenue")({
  head: () => ({
    meta: [
      { title: "Revenue Analysis · ITF 2024 Scorecard" },
      { name: "description", content: "Revenue generation comparison 2023 vs 2024 across Training Contribution, Course Fee and Other Income, with area-office performance." },
      { property: "og:title", content: "ITF 2024 – Revenue Analysis" },
      { property: "og:description", content: "Comparative analysis of revenue generated by Category A, B and C area offices for the Industrial Training Fund." },
    ],
  }),
  component: Revenue,
});

function Revenue() {
  const { year, hasData } = useYear();
  if (!hasData(year)) {
    return (
      <DashboardLayout title="Revenue Analysis" subtitle={`FY ${year}`}>
        <EmptyState year={year} hint="No revenue records for this year. Add revenue rows / area-office data via the admin panel." />
      </DashboardLayout>
    );
  }

  const tc = areaRevenue.filter((r) => r.stream === "Training Contribution");
  const cf = areaRevenue.filter((r) => r.stream === "Course Fee");
  const tcByCat = (["A","B","C"] as const).map((c) => {
    const rows = tc.filter((r) => r.category === c);
    return {
      category: `Category ${c}`,
      "2023": rows.reduce((s, r) => s + r.actual23, 0) / 1_000_000_000,
      "2024": rows.reduce((s, r) => s + r.actual24, 0) / 1_000_000_000,
    };
  });

  const topGrowth = [...tc].map((r) => ({ ...r, g: growth(r.actual24, r.actual23) })).sort((a, b) => b.g - a.g).slice(0, 5);
  const bottomGrowth = [...tc].map((r) => ({ ...r, g: growth(r.actual24, r.actual23) })).sort((a, b) => a.g - b.g).slice(0, 5);

  const streamMix = [
    { name: "Training Contribution", value: headlineRevenue[0].actual24 },
    { name: "Course Fee", value: headlineRevenue[1].actual24 },
    { name: "Other Income", value: headlineRevenue[2].actual24 },
  ];
  const COLORS = ["#00723F", "#C8102E", "#E6B422"];

  return (
    <DashboardLayout title="Revenue Analysis" subtitle="Part Two of the report — comparative analysis of revenue generated in 2023 vs 2024 across all area offices.">
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Kpi label="Training Contribution 2024" value={fmtNaira(headlineRevenue[0].actual24)} sub="+11.2% vs 2023" tone="good" />
        <Kpi label="Course Fee 2024" value={fmtNaira(headlineRevenue[1].actual24)} sub="+5.3% vs 2023" tone="warn" />
        <Kpi label="Other Income 2024" value={fmtNaira(headlineRevenue[2].actual24)} sub="-70.1% vs 2023" tone="bad" />
        <Kpi label="Total Generated 2024" value={fmtNaira(headlineRevenue.reduce((s,r)=>s+r.actual24,0))} sub="Sum of all three streams" tone="good" />
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        <Section kicker="Distribution" title="2024 Revenue Mix">
          <div className="h-72">
            <ResponsiveContainer>
              <PieChart>
                <Pie data={streamMix} dataKey="value" nameKey="name" innerRadius={55} outerRadius={95} label={(d:any) => `${(d.percent*100).toFixed(1)}%`}>
                  {streamMix.map((_, i) => <Cell key={i} fill={COLORS[i]} />)}
                </Pie>
                <Tooltip formatter={(v: number) => fmtNaira(v)} />
                <Legend />
              </PieChart>
            </ResponsiveContainer>
          </div>
          <Note>Training Contribution makes up roughly 98% of total revenue. The Fund's revenue base is heavily concentrated and remains structurally dependent on the 1% mandatory levy.</Note>
        </Section>
        <Section kicker="By Category" title="Training Contribution by Office Category (₦ Billions)">
          <div className="h-72">
            <ResponsiveContainer>
              <BarChart data={tcByCat} margin={{ top: 8, right: 16, left: 0, bottom: 0 }}>
                <CartesianGrid stroke="#e5e7eb" vertical={false} />
                <XAxis dataKey="category" tick={{ fontSize: 12 }} />
                <YAxis tick={{ fontSize: 12 }} unit="B" />
                <Tooltip formatter={(v:number)=>`₦${v.toFixed(2)}B`} />
                <Legend />
                <Bar dataKey="2023" fill="#7a8a99" />
                <Bar dataKey="2024" fill="#00723F" />
              </BarChart>
            </ResponsiveContainer>
          </div>
          <Note>Category A offices (the big-city units) deliver ≈ 88% of Training Contribution — V/Island, Abuja and Lagos Island alone exceed ₦32 B in 2024.</Note>
        </Section>
      </div>

      <Section kicker="Performance" title="Training Contribution — every Area Office, 2023 vs 2024">
        <DataTable
          headers={["Cat", "Area Office", "2023 Actual", "2023 %", "2024 Actual", "2024 %", "YoY"]}
          rows={tc.map((r) => [
            r.category,
            r.office,
            fmtNaira(r.actual23),
            <PctBar key="a" value={achievement(r.actual23, r.target23)} />,
            fmtNaira(r.actual24),
            <PctBar key="b" value={achievement(r.actual24, r.target24)} />,
            <span key="g" className={growth(r.actual24, r.actual23) >= 0 ? "text-itf-green font-semibold" : "text-itf-red font-semibold"}>
              {growth(r.actual24, r.actual23).toFixed(1)}%
            </span>,
          ])}
        />
      </Section>

      <div className="grid md:grid-cols-2 gap-6">
        <Section kicker="Top 5" title="Highest Growth Offices (Training Contribution)">
          <ol className="text-sm space-y-1">
            {topGrowth.map((r, i) => (
              <li key={r.office} className="flex justify-between border-b border-itf-rule py-1">
                <span><b className="text-itf-green">{i+1}.</b> {r.office} <span className="text-[10px] uppercase text-itf-ink/60">Cat {r.category}</span></span>
                <span className="text-itf-green font-semibold">+{r.g.toFixed(1)}%</span>
              </li>
            ))}
          </ol>
        </Section>
        <Section kicker="Bottom 5" title="Largest Declines (Training Contribution)">
          <ol className="text-sm space-y-1">
            {bottomGrowth.map((r, i) => (
              <li key={r.office} className="flex justify-between border-b border-itf-rule py-1">
                <span><b className="text-itf-red">{i+1}.</b> {r.office} <span className="text-[10px] uppercase text-itf-ink/60">Cat {r.category}</span></span>
                <span className="text-itf-red font-semibold">{r.g.toFixed(1)}%</span>
              </li>
            ))}
          </ol>
        </Section>
      </div>

      <Section kicker="Course Fee" title="Course Fee — Category A & B Area Offices">
        <DataTable
          headers={["Cat", "Area Office", "2023 Actual", "2023 %", "2024 Actual", "2024 %", "YoY"]}
          rows={cf.map((r) => [
            r.category, r.office,
            fmtNaira(r.actual23),
            <PctBar key="a" value={achievement(r.actual23, r.target23)} />,
            fmtNaira(r.actual24),
            <PctBar key="b" value={achievement(r.actual24, r.target24)} />,
            <span key="g" className={growth(r.actual24, r.actual23) >= 0 ? "text-itf-green font-semibold" : "text-itf-red font-semibold"}>{growth(r.actual24, r.actual23).toFixed(1)}%</span>,
          ])}
        />
        <Note>Course Fee delivery is uneven — Lagos Island (174%), Lafia (118%), Abeokuta (169%) over-delivered; Lekki, Rumuokuta, Badagry, Enugu remained below 35% of target. Underperforming centres should be reviewed for pricing, demand and operating model.</Note>
      </Section>
    </DashboardLayout>
  );
}
