import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { DashboardLayout } from "@/components/dashboard/DashboardLayout";
import { EnhancedKpi, Kpi, Note, Section, DataTable, PctBar, EmptyState } from "@/components/dashboard/widgets";
import { NigeriaRevenueMap } from "@/components/dashboard/NigeriaRevenueMap";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { fmtNaira, growth, achievement } from "@/data/itf2024";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Legend, CartesianGrid, PieChart, Pie, Cell } from "recharts";
import { useYear } from "@/lib/year-context";
import { supabase } from "@/integrations/supabase/client";
import { buildRevenueAggregation } from "@/lib/revenue-data";

const formatChartAmount = (value: number) => {
  const abs = Math.abs(value);

  if (abs < 1) {
    const millions = value * 1000;
    return `₦${millions.toLocaleString(undefined, { maximumFractionDigits: millions >= 100 ? 0 : 1 })}M`;
  }

  return `₦${value.toFixed(2)}B`;
};

const formatChartAxis = (value: number) => {
  const abs = Math.abs(value);

  if (abs < 1) {
    const millions = value * 1000;
    return `${millions.toLocaleString(undefined, { maximumFractionDigits: millions >= 100 ? 0 : 1 })}M`;
  }

  return `${value.toFixed(2)}B`;
};

function RevenueTooltip({ active, payload, label, prevYearLabel, currentYearLabel }: { active?: boolean; payload?: Array<any>; label?: string | number; prevYearLabel: string; currentYearLabel: string }) {
  if (!active || !payload?.length) return null;

  const firstEntry = payload[0] as any;
  const row = firstEntry?.payload as Record<string, any> | undefined;
  if (!row) return null;

  const previousValue = Number(row.prev ?? row.previous ?? 0);
  const currentValue = Number(row.current ?? row.value ?? 0);
  const delta = currentValue - previousValue;
  const pct = previousValue === 0 ? 0 : (delta / previousValue) * 100;

  return (
    <div className="rounded-lg border border-itf-rule bg-white/95 px-3 py-2 text-sm shadow-lg">
      <div className="mb-2 font-semibold text-itf-ink">{String(label ?? "Value")}</div>
      <div className="space-y-1">
        <div className="flex items-center justify-between gap-3">
          <span className="font-medium text-itf-red">{prevYearLabel}</span>
          <span className="font-semibold text-itf-red">{formatChartAmount(previousValue)}</span>
        </div>
        <div className="flex items-center justify-between gap-3">
          <span className="font-medium text-itf-green">{currentYearLabel}</span>
          <span className="font-semibold text-itf-green">{formatChartAmount(currentValue)}</span>
        </div>
        <div className={`flex items-center justify-between gap-3 ${delta >= 0 ? "text-itf-green" : "text-itf-red"}`}>
          <span className="font-medium">Difference</span>
          <span className="font-semibold">{delta >= 0 ? "+" : ""}{formatChartAmount(Math.abs(delta))}</span>
        </div>
        <div className={`flex items-center justify-between gap-3 ${pct >= 0 ? "text-itf-green" : "text-itf-red"}`}>
          <span className="font-medium">YoY</span>
          <span className="font-semibold inline-flex items-center gap-1">
            <span>{pct >= 0 ? "▲" : "▼"}</span>
            <span>{pct >= 0 ? "+" : ""}{pct.toFixed(1)}%</span>
          </span>
        </div>
      </div>
    </div>
  );
}

export const Route = createFileRoute("/revenue")({
  head: () => ({
    meta: [
      { title: "Income Analysis · ITF 2024 Scorecard" },
      { name: "description", content: "Income generation comparison across the selected year and the previous year for headline income and area-office performance." },
      { property: "og:title", content: "ITF 2024 – Income Analysis" },
      { property: "og:description", content: "Comparative analysis of income generated by Category A, B and C area offices for the Industrial Training Fund." },
    ],
  }),
  component: Revenue,
});

function Revenue() {
  const { year, hasData, yearsWithData } = useYear();
  const prevYear = [...yearsWithData].filter((y) => y < year).pop() ?? null;

  const { data: areaCurrent = [] as any[] } = useQuery({
    queryKey: ["area_revenue", year],
    enabled: year > 0,
    queryFn: async () => {
      const { data } = await supabase.from("area_revenue").select("*").eq("year", year).order("office");
      return data ?? [];
    },
  });

  const { data: areaPrev = [] as any[] } = useQuery({
    queryKey: ["area_revenue", prevYear],
    enabled: !!prevYear,
    queryFn: async () => {
      const { data } = await supabase.from("area_revenue").select("*").eq("year", prevYear as number).order("office");
      return data ?? [];
    },
  });

  if (!year || !hasData(year)) {
    return (
      <DashboardLayout title="Income Analysis" subtitle={`TY ${year}`}>
        <EmptyState year={year} hint="No income records for this year. Add income rows / area-office data via the admin panel." />
      </DashboardLayout>
    );
  }

  const safeGrowth = (current: number, previous: number) => (previous === 0 ? 0 : growth(current, previous));
  const safeAchievement = (actual: number, target: number) => (target === 0 ? 0 : achievement(actual, target));
  const aggregation = buildRevenueAggregation(areaCurrent, areaPrev);
  const revenueTotals = aggregation.totals;
  const streamMap = Object.fromEntries(revenueTotals.map((row) => [row.stream, row]));
  const tc = streamMap["Training Contribution"];
  const cf = streamMap["Course Fee"];
  const oi = streamMap["Other Income"];
  const prevLabel = prevYear ? String(prevYear) : "Previous";
  const currentLabel = String(year);

  const tcByCat = (["A", "B", "C"] as const).map((c) => {
    const section = aggregation.sections.find((item) => item.id === `category-${c}`);
    const training = section?.rows.find((row) => row.stream === "Training Contribution");
    const prevValue = (training?.previousActual ?? 0) / 1_000_000_000;
    const currentValue = (training?.actual ?? 0) / 1_000_000_000;

    return {
      category: `Category ${c}`,
      prev: prevValue,
      current: currentValue,
      [prevLabel]: prevValue,
      [currentLabel]: currentValue,
    };
  });

  const trainingSectionRows = aggregation.sections.find((item) => item.id === "category-A")?.rows ?? [];
  const topGrowth = [...(aggregation.sections.find((item) => item.id === "category-A")?.rows ?? [])].map((r) => ({ category: "A", office: r.stream, currentActual: r.actual, currentTarget: r.target, prevActual: r.previousActual, prevTarget: r.previousTarget, g: safeGrowth(r.actual, r.previousActual) })).sort((a, b) => b.g - a.g).slice(0, 5);
  const bottomGrowth = [...(aggregation.sections.find((item) => item.id === "category-A")?.rows ?? [])].map((r) => ({ category: "A", office: r.stream, currentActual: r.actual, currentTarget: r.target, prevActual: r.previousActual, prevTarget: r.previousTarget, g: safeGrowth(r.actual, r.previousActual) })).sort((a, b) => a.g - b.g).slice(0, 5);

  const streamMix = [
    { name: "Training Contribution", value: Number(tc?.actual ?? 0) },
    { name: "Course Fee", value: Number(cf?.actual ?? 0) },
    { name: "Other Income", value: Number(oi?.actual ?? 0) },
  ];
  const hasRevenueValues = streamMix.some((item) => Number(item.value) > 0);
  const COLORS = ["#00723F", "#C8102E", "#E6B422"];

  const currentTotal = revenueTotals.reduce((sum, row) => sum + row.actual, 0);
  const previousTotal = revenueTotals.reduce((sum, row) => sum + row.previousActual, 0);
  const currentTargetTotal = revenueTotals.reduce((sum, row) => sum + row.target, 0);

  const kpiTone = (pct: number) => pct >= 100 ? "good" : pct >= 70 ? "warn" : "bad";
  const currentPct = currentTargetTotal > 0 ? (currentTotal / currentTargetTotal) * 100 : 0;

  // Build a flat list of area-office rows only for the comparative chart and ranking
  const officeBreakdown = aggregation.sections
    .filter((s) => s.kind === "category")
    .flatMap((s) => s.breakdown);
  const officeRows = [...officeBreakdown].sort((a, b) => b.currentActual - a.currentActual).map((o) => ({
    office: o.office,
    prev: Number(o.previousActual ?? 0) / 1_000_000_000,
    current: Number(o.currentActual ?? 0) / 1_000_000_000,
  }));
  const officeChartHeight = Math.max(340, officeRows.length * 36);

  const corpOfficeRow = aggregation.sections
    .flatMap((s) => s.breakdown)
    .find((b) => String(b.office).trim() === "Corporate Office Abuja") ?? null;

  return (
    <DashboardLayout title="Income Analysis" subtitle={prevYear ? `Live income data for TY ${year} with TY ${prevYear} comparisons.` : `Live income data for TY ${year}.`}>
      <div>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4">
          <EnhancedKpi
          label="Total Generated"
          currentValue={currentTotal}
          previousValue={prevYear ? previousTotal : undefined}
          currentYear={year}
          previousYear={prevYear}
          formatValue={fmtNaira}
          tone={currentPct >= 100 ? "good" : currentPct >= 70 ? "warn" : "bad"}
          noteText="Sum of live income streams"
        />
        <EnhancedKpi
          label="Training Contribution"
          currentValue={Number(tc?.actual ?? 0)}
          previousValue={prevYear ? Number(tc?.previousActual ?? 0) : undefined}
          currentYear={year}
          previousYear={prevYear}
          formatValue={fmtNaira}
          tone={kpiTone(Number(tc?.pct ?? 0))}
          noteText={prevYear ? `Live Training Contribution income for TY ${year} compared against TY ${prevYear}.` : "Live from database."}
        />
        <EnhancedKpi
          label="Course Fee"
          currentValue={Number(cf?.actual ?? 0)}
          previousValue={prevYear ? Number(cf?.previousActual ?? 0) : undefined}
          currentYear={year}
          previousYear={prevYear}
          formatValue={fmtNaira}
          tone={kpiTone(Number(cf?.pct ?? 0))}
          noteText={prevYear ? `Live Course Fee stream total for TY ${year} compared against TY ${prevYear}.` : "Live from database."}
        />
        <EnhancedKpi
          label="Other Income"
          currentValue={Number(oi?.actual ?? 0)}
          previousValue={prevYear ? Number(oi?.previousActual ?? 0) : undefined}
          currentYear={year}
          previousYear={prevYear}
          formatValue={fmtNaira}
          tone={kpiTone(Number(oi?.pct ?? 0))}
          noteText={prevYear ? `Live Other Income stream total for TY ${year} compared against TY ${prevYear}.` : "Live from database."}
        />
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        <Section kicker="Distribution" title={`${year} Income Mix`}>
          <div className="h-72">
            <ResponsiveContainer>
              <PieChart>
                <Pie data={streamMix} dataKey="value" nameKey="name" innerRadius={55} outerRadius={95} label={(d: any) => `${(d.percent * 100).toFixed(1)}%`}>
                  {streamMix.map((_, i) => <Cell key={i} fill={COLORS[i]} />)}
                </Pie>
                <Tooltip formatter={(v: number) => fmtNaira(v)} />
                <Legend />
              </PieChart>
            </ResponsiveContainer>
          </div>
          <Note>{hasRevenueValues ? "Income mix is drawn from the live headline rows in the database for the selected year." : "No income data is available for this year yet."}</Note>
        </Section>
        <Section kicker="By Category" title="Training Contribution by Office Category (₦ Billions)">
          <div className="h-72">
            <ResponsiveContainer>
              <BarChart data={tcByCat} margin={{ top: 8, right: 16, left: 0, bottom: 0 }}>
                <CartesianGrid stroke="#e5e7eb" vertical={false} />
                <XAxis dataKey="category" tick={{ fontSize: 12 }} />
                <YAxis tick={{ fontSize: 12 }} tickFormatter={(value: number) => formatChartAxis(Number(value))} />
                <Tooltip content={<RevenueTooltip prevYearLabel={prevLabel} currentYearLabel={currentLabel} />} />
                <Legend />
                <Bar dataKey={prevLabel} fill="#C8102E" />
                <Bar dataKey={currentLabel} fill="#00723F" />
              </BarChart>
            </ResponsiveContainer>
          </div>
          <Note>{hasRevenueValues ? "Category totals are built from the most recent area-office rows stored for the selected year and the previous year." : "No area-office income data is available for this year yet."}</Note>
        </Section>
      </div>

      <Section kicker="Map" title="ITF Income by State">
        <NigeriaRevenueMap rows={areaCurrent} />
      </Section>

      <Section kicker="All Offices" title="Area Offices — Income Comparison (₦B)">
        <div>
          <div style={{ width: "100%", height: officeChartHeight }}>
            <ResponsiveContainer width="100%" height={officeChartHeight}>
              <BarChart layout="vertical" data={officeRows} margin={{ top: 12, right: 16, left: 160, bottom: 12 }}>
                <CartesianGrid stroke="#e5e7eb" vertical={false} />
                <XAxis type="number" tick={{ fontSize: 12 }} unit="B" />
                <YAxis dataKey="office" type="category" width={160} tick={{ fontSize: 12 }} />
                <Tooltip content={<RevenueTooltip prevYearLabel={prevLabel} currentYearLabel={currentLabel} />} />
                <Legend />
                <Bar dataKey="prev" name={`${prevLabel} Actual`} fill="#C8102E" />
                <Bar dataKey="current" name={`${currentLabel} Actual`} fill="#00723F" />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </Section>

      <div className="grid md:grid-cols-2 gap-6">
        <Section kicker="Ranking" title={`Top 10 Offices by Income — TY ${year} (₦B)`}>
          <div className="h-72">
            <ResponsiveContainer>
              <BarChart data={[...aggregation.sections.filter((section) => section.kind === "category").flatMap((section) => section.breakdown)].sort((a, b) => b.currentActual - a.currentActual).slice(0, 10).map((item) => ({ office: item.office, value: item.currentActual / 1_000_000_000 }))} margin={{ top: 8, right: 16, left: 0, bottom: 70 }}>
                <CartesianGrid stroke="#e5e7eb" vertical={false} />
                <XAxis dataKey="office" tick={{ fontSize: 12 }} angle={-18} textAnchor="end" height={70} />
                <YAxis tick={{ fontSize: 12 }} unit="B" />
                <Tooltip formatter={(v: number) => `₦${v.toFixed(2)}B`} />
                <Bar dataKey="value" fill="#00723F" radius={[6, 6, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </Section>
        <Section kicker="Ranking" title={`Bottom 10 Offices by Income — TY ${year} (₦B)`}>
          <div className="h-72">
            <ResponsiveContainer>
              <BarChart data={[...aggregation.sections.filter((section) => section.kind === "category").flatMap((section) => section.breakdown)].sort((a, b) => a.currentActual - b.currentActual).slice(0, 10).map((item) => ({ office: item.office, value: item.currentActual / 1_000_000_000 }))} margin={{ top: 8, right: 16, left: 0, bottom: 70 }}>
                <CartesianGrid stroke="#e5e7eb" vertical={false} />
                <XAxis dataKey="office" tick={{ fontSize: 12 }} angle={-18} textAnchor="end" height={70} />
                <YAxis tick={{ fontSize: 12 }} unit="B" />
                <Tooltip formatter={(v: number) => `₦${v.toFixed(2)}B`} />
                <Bar dataKey="value" fill="#C8102E" radius={[6, 6, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </Section>
      </div>

      {/* Revenue by Stream section removed per request */}

      {/* Top 5 / Bottom 5 growth lists removed per request */}

      <Section kicker="Category Structure" title={`Income by Category — ${year}`}>
        <div className="space-y-3">
          <Note>Expand any card to inspect each office in that category or training centre and compare the current year against the previous year.</Note>
          <Accordion type="multiple" className="space-y-3">
            {aggregation.sections.map((section) => {
              const currentSectionTotal = section.rows.reduce((sum, row) => sum + row.actual, 0);
              return (
                <AccordionItem key={section.id} value={section.id} className="border border-itf-rule rounded-lg overflow-hidden bg-white">
                  <AccordionTrigger className="px-4 py-3 hover:no-underline">
                    <div className="flex flex-1 items-center justify-between gap-3">
                      <div className="text-left">
                        <div className="font-semibold text-itf-green">{section.title}</div>
                        <div className="text-xs text-itf-ink/60">{section.kind === "category" ? "State/office breakdown" : "Training centre detail"}</div>
                      </div>
                      <div className="text-right text-sm font-semibold text-itf-ink">
                        <div>{fmtNaira(currentSectionTotal)}</div>
                        <div className="text-[11px] text-itf-ink/60">{year} total</div>
                      </div>
                    </div>
                  </AccordionTrigger>
                  <AccordionContent className="px-4 pb-4">
                    <div className="overflow-x-auto">
                      <DataTable
                        stickyHeader
                        className="max-h-[32rem]"
                        headers={["Office", "Stream", `${prevYear ?? "Prev"} Target`, `${prevYear ?? "Prev"} Actual`, `${prevYear ?? "Prev"} % achieved`, `${year} Target`, `${year} Actual`, `${year} Actual`, `${year} % achieved`, "YoY"]}
                        rows={section.breakdown
                          .filter((office) => !(section.kind === "training-centre" && String(office.office).trim() === "Corporate Office Abuja"))
                          .flatMap((office) => office.streams.map((stream) => {
                          const prevTarget = Number(stream.previousTarget ?? 0);
                          const prevActual = Number(stream.previousActual ?? 0);
                          const prevPct = safeAchievement(prevActual, prevTarget);
                          const curTarget = Number(stream.target ?? 0);
                          const curActual = Number(stream.actual ?? 0);
                          const curPct = safeAchievement(curActual, curTarget);
                          const yoy = safeGrowth(curActual, prevActual);
                          const absY = Math.min(Math.abs(yoy), 200);
                          const barPct = (absY / 200) * 100;
                          const barColor = yoy >= 0 ? "bg-itf-green" : "bg-itf-red";

                          return [
                            office.office,
                            stream.stream,
                            fmtNaira(prevTarget),
                            fmtNaira(prevActual),
                            <PctBar key={`${section.id}-${office.office}-${stream.stream}-prevpct`} value={prevPct} />,
                            fmtNaira(curTarget),
                            fmtNaira(curActual),
                            <PctBar key={`${section.id}-${office.office}-${stream.stream}-curpct`} value={curPct} />,
                            <div key={`${section.id}-${office.office}-${stream.stream}-yoy`} className="flex items-center gap-3">
                              <div className={`${yoy >= 0 ? "text-itf-green" : "text-itf-red"} font-semibold text-sm`}>{yoy >= 0 ? "▲" : "▼"}{yoy.toFixed(1)}%</div>
                              <div className="flex-1 min-w-[100px] max-w-[140px] h-2 bg-itf-rule rounded-sm overflow-hidden">
                                <div className={`${barColor} h-full`} style={{ width: `${barPct}%` }} />
                              </div>
                            </div>,
                          ];
                        }))}
                      />
                    </div>
                    <div className="mt-6">
                      <div className="text-sm font-semibold text-itf-ink mb-3">
                        {section.kind === "training-centre" ? "Training Centres — Income Comparison" : "Office Income Comparison"}
                      </div>
                      <div className="h-[420px]">
                        <ResponsiveContainer width="100%" height="100%">
                          <BarChart
                            layout="vertical"
                            data={[...section.breakdown]
                              .filter((item) => !(section.kind === "training-centre" && String(item.office).trim() === "Corporate Office Abuja"))
                              .sort((a, b) => b.currentActual - a.currentActual).map((item) => ({
                              office: item.office,
                              prev: item.previousActual / 1_000_000_000,
                              current: item.currentActual / 1_000_000_000,
                            }))}
                            margin={{ top: 12, right: 16, left: 160, bottom: 12 }}
                          >
                            <CartesianGrid stroke="#e5e7eb" vertical={false} />
                            <XAxis type="number" tick={{ fontSize: 12 }} tickFormatter={(value: number) => formatChartAxis(Number(value))} />
                            <YAxis dataKey="office" type="category" width={160} tick={{ fontSize: 12 }} />
                            <Tooltip content={<RevenueTooltip prevYearLabel={prevLabel} currentYearLabel={currentLabel} />} />
                            <Legend />
                            <Bar dataKey="prev" name={`${prevLabel} Actual`} fill="#C8102E" />
                            <Bar dataKey="current" name={`${currentLabel} Actual`} fill="#00723F" />
                          </BarChart>
                        </ResponsiveContainer>
                      </div>
                    </div>
                  </AccordionContent>
                </AccordionItem>
              );
            })}
            {/* Dedicated Corporate Office Abuja accordion */}
            <AccordionItem key="corporate-office-abuja" value="corporate-office-abuja" className="border border-itf-rule rounded-lg overflow-hidden bg-white">
              <AccordionTrigger className="px-4 py-3 hover:no-underline">
                <div className="flex flex-1 items-center justify-between gap-3">
                  <div className="text-left">
                    <div className="font-semibold text-itf-green">Corporate Office Abuja</div>
                    <div className="text-xs text-itf-ink/60">Training centre detail</div>
                  </div>
                  <div className="text-right text-sm font-semibold text-itf-ink">
                    <div>{fmtNaira(Number(corpOfficeRow?.currentActual ?? 0))}</div>
                    <div className="text-[11px] text-itf-ink/60">{year} total</div>
                  </div>
                </div>
              </AccordionTrigger>
              <AccordionContent className="px-4 pb-4">
                {corpOfficeRow ? (
                  <>
                    <div className="overflow-x-auto">
                      <DataTable
                        stickyHeader
                        className="max-h-[32rem]"
                        headers={["Office", "Stream", `${prevYear ?? "Prev"} Target`, `${prevYear ?? "Prev"} Actual`, `${prevYear ?? "Prev"} % achieved`, `${year} Target`, `${year} Actual`, `${year} % achieved`, "YoY"]}
                        rows={corpOfficeRow.streams.map((stream: any) => {
                          const prevTarget = Number(stream.previousTarget ?? 0);
                          const prevActual = Number(stream.previousActual ?? 0);
                          const prevPct = safeAchievement(prevActual, prevTarget);
                          const curTarget = Number(stream.target ?? 0);
                          const curActual = Number(stream.actual ?? 0);
                          const curPct = safeAchievement(curActual, curTarget);
                          const yoy = safeGrowth(curActual, prevActual);
                          const absY = Math.min(Math.abs(yoy), 200);
                          const barPct = (absY / 200) * 100;
                          const barColor = yoy >= 0 ? "bg-itf-green" : "bg-itf-red";

                          return [
                            corpOfficeRow.office,
                            stream.stream,
                            fmtNaira(prevTarget),
                            fmtNaira(prevActual),
                            <PctBar key={`corp-${stream.stream}-prevpct`} value={prevPct} />,
                            fmtNaira(curTarget),
                            fmtNaira(curActual),
                            <PctBar key={`corp-${stream.stream}-curpct`} value={curPct} />,
                            <div key={`corp-${stream.stream}-yoy`} className="flex items-center gap-3">
                              <div className={`${yoy >= 0 ? "text-itf-green" : "text-itf-red"} font-semibold text-sm`}>{yoy >= 0 ? "▲" : "▼"}{yoy.toFixed(1)}%</div>
                              <div className="flex-1 min-w-[100px] max-w-[140px] h-2 bg-itf-rule rounded-sm overflow-hidden">
                                <div className={`${barColor} h-full`} style={{ width: `${barPct}%` }} />
                              </div>
                            </div>,
                          ];
                        })}
                      />
                    </div>
                    <div className="mt-6">
                      <div className="text-sm font-semibold text-itf-ink mb-3">Training Centres — Income Comparison</div>
                      <div className="h-[420px]">
                        <ResponsiveContainer width="100%" height="100%">
                          <BarChart
                            layout="vertical"
                            data={[{
                              office: corpOfficeRow.office,
                              prev: Number(corpOfficeRow.previousActual ?? 0) / 1_000_000_000,
                              current: Number(corpOfficeRow.currentActual ?? 0) / 1_000_000_000,
                            }]}
                            margin={{ top: 12, right: 16, left: 160, bottom: 12 }}
                          >
                            <CartesianGrid stroke="#e5e7eb" vertical={false} />
                            <XAxis type="number" tick={{ fontSize: 12 }} tickFormatter={(value: number) => formatChartAxis(Number(value))} />
                            <YAxis dataKey="office" type="category" width={160} tick={{ fontSize: 12 }} />
                            <Tooltip content={<RevenueTooltip prevYearLabel={prevLabel} currentYearLabel={currentLabel} />} />
                            <Legend />
                            <Bar dataKey="prev" name={`${prevLabel} Actual`} fill="#C8102E" />
                            <Bar dataKey="current" name={`${currentLabel} Actual`} fill="#00723F" />
                          </BarChart>
                        </ResponsiveContainer>
                      </div>
                    </div>
                  </>
                ) : (
                  <div className="p-6 text-sm text-itf-ink/70">No Corporate Office Abuja revenue rows found for the selected year.</div>
                )}
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </div>
      </Section>
    </div>
  </DashboardLayout>
  );
}
