/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ExecutiveDeckRouteImport } from './routes/executive-deck'
import { Route as DetailedRouteImport } from './routes/detailed'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminResetRouteImport } from './routes/admin.reset'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminForgotRouteImport } from './routes/admin.forgot'

const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveDeckRoute = ExecutiveDeckRouteImport.update({
  id: '/executive-deck',
  path: '/executive-deck',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailedRoute = DetailedRouteImport.update({
  id: '/detailed',
  path: '/detailed',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetRoute = AdminResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForgotRoute = AdminForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/detailed': typeof DetailedRoute
  '/executive-deck': typeof ExecutiveDeckRoute
  '/insights': typeof InsightsRoute
  '/performance': typeof PerformanceRoute
  '/revenue': typeof RevenueRoute
  '/training': typeof TrainingRoute
  '/validation': typeof ValidationRoute
  '/admin/forgot': typeof AdminForgotRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/detailed': typeof DetailedRoute
  '/executive-deck': typeof ExecutiveDeckRoute
  '/insights': typeof InsightsRoute
  '/performance': typeof PerformanceRoute
  '/revenue': typeof RevenueRoute
  '/training': typeof TrainingRoute
  '/validation': typeof ValidationRoute
  '/admin/forgot': typeof AdminForgotRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/detailed': typeof DetailedRoute
  '/executive-deck': typeof ExecutiveDeckRoute
  '/insights': typeof InsightsRoute
  '/performance': typeof PerformanceRoute
  '/revenue': typeof RevenueRoute
  '/training': typeof TrainingRoute
  '/validation': typeof ValidationRoute
  '/admin/forgot': typeof AdminForgotRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/detailed'
    | '/executive-deck'
    | '/insights'
    | '/performance'
    | '/revenue'
    | '/training'
    | '/validation'
    | '/admin/forgot'
    | '/admin/login'
    | '/admin/reset'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/detailed'
    | '/executive-deck'
    | '/insights'
    | '/performance'
    | '/revenue'
    | '/training'
    | '/validation'
    | '/admin/forgot'
    | '/admin/login'
    | '/admin/reset'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/detailed'
    | '/executive-deck'
    | '/insights'
    | '/performance'
    | '/revenue'
    | '/training'
    | '/validation'
    | '/admin/forgot'
    | '/admin/login'
    | '/admin/reset'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  DetailedRoute: typeof DetailedRoute
  ExecutiveDeckRoute: typeof ExecutiveDeckRoute
  InsightsRoute: typeof InsightsRoute
  PerformanceRoute: typeof PerformanceRoute
  RevenueRoute: typeof RevenueRoute
  TrainingRoute: typeof TrainingRoute
  ValidationRoute: typeof ValidationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-deck': {
      id: '/executive-deck'
      path: '/executive-deck'
      fullPath: '/executive-deck'
      preLoaderRoute: typeof ExecutiveDeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detailed': {
      id: '/detailed'
      path: '/detailed'
      fullPath: '/detailed'
      preLoaderRoute: typeof DetailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset': {
      id: '/admin/reset'
      path: '/reset'
      fullPath: '/admin/reset'
      preLoaderRoute: typeof AdminResetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forgot': {
      id: '/admin/forgot'
      path: '/forgot'
      fullPath: '/admin/forgot'
      preLoaderRoute: typeof AdminForgotRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminForgotRoute: typeof AdminForgotRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetRoute: typeof AdminResetRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminForgotRoute: AdminForgotRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminResetRoute: AdminResetRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  DetailedRoute: DetailedRoute,
  ExecutiveDeckRoute: ExecutiveDeckRoute,
  InsightsRoute: InsightsRoute,
  PerformanceRoute: PerformanceRoute,
  RevenueRoute: RevenueRoute,
  TrainingRoute: TrainingRoute,
  ValidationRoute: ValidationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
