/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as StaffSchoolRouteImport } from './routes/staff-school'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as ProjectionsRouteImport } from './routes/projections'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ExecutiveDeckRouteImport } from './routes/executive-deck'
import { Route as DetailedRouteImport } from './routes/detailed'
import { Route as BkRouteImport } from './routes/bk'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PerformanceIndexRouteImport } from './routes/performance/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PerformanceKraRouteImport } from './routes/performance/$kra'
import { Route as AdminResetRouteImport } from './routes/admin.reset'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminForgotRouteImport } from './routes/admin.forgot'

const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSchoolRoute = StaffSchoolRouteImport.update({
  id: '/staff-school',
  path: '/staff-school',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectionsRoute = ProjectionsRouteImport.update({
  id: '/projections',
  path: '/projections',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveDeckRoute = ExecutiveDeckRouteImport.update({
  id: '/executive-deck',
  path: '/executive-deck',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailedRoute = DetailedRouteImport.update({
  id: '/detailed',
  path: '/detailed',
  getParentRoute: () => rootRouteImport,
} as any)
const BkRoute = BkRouteImport.update({
  id: '/bk',
  path: '/bk',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceIndexRoute = PerformanceIndexRouteImport.update({
  id: '/performance/',
  path: '/performance/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PerformanceKraRoute = PerformanceKraRouteImport.update({
  id: '/performance/$kra',
  path: '/performance/$kra',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetRoute = AdminResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForgotRoute = AdminForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/bk': typeof BkRoute
  '/detailed': typeof DetailedRoute
  '/executive-deck': typeof ExecutiveDeckRoute
  '/insights': typeof InsightsRoute
  '/projections': typeof ProjectionsRoute
  '/revenue': typeof RevenueRoute
  '/staff-school': typeof StaffSchoolRoute
  '/training': typeof TrainingRoute
  '/validation': typeof ValidationRoute
  '/admin/forgot': typeof AdminForgotRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset': typeof AdminResetRoute
  '/performance/$kra': typeof PerformanceKraRoute
  '/admin/': typeof AdminIndexRoute
  '/performance/': typeof PerformanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bk': typeof BkRoute
  '/detailed': typeof DetailedRoute
  '/executive-deck': typeof ExecutiveDeckRoute
  '/insights': typeof InsightsRoute
  '/projections': typeof ProjectionsRoute
  '/revenue': typeof RevenueRoute
  '/staff-school': typeof StaffSchoolRoute
  '/training': typeof TrainingRoute
  '/validation': typeof ValidationRoute
  '/admin/forgot': typeof AdminForgotRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset': typeof AdminResetRoute
  '/performance/$kra': typeof PerformanceKraRoute
  '/admin': typeof AdminIndexRoute
  '/performance': typeof PerformanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/bk': typeof BkRoute
  '/detailed': typeof DetailedRoute
  '/executive-deck': typeof ExecutiveDeckRoute
  '/insights': typeof InsightsRoute
  '/projections': typeof ProjectionsRoute
  '/revenue': typeof RevenueRoute
  '/staff-school': typeof StaffSchoolRoute
  '/training': typeof TrainingRoute
  '/validation': typeof ValidationRoute
  '/admin/forgot': typeof AdminForgotRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset': typeof AdminResetRoute
  '/performance/$kra': typeof PerformanceKraRoute
  '/admin/': typeof AdminIndexRoute
  '/performance/': typeof PerformanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/bk'
    | '/detailed'
    | '/executive-deck'
    | '/insights'
    | '/projections'
    | '/revenue'
    | '/staff-school'
    | '/training'
    | '/validation'
    | '/admin/forgot'
    | '/admin/login'
    | '/admin/reset'
    | '/performance/$kra'
    | '/admin/'
    | '/performance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/bk'
    | '/detailed'
    | '/executive-deck'
    | '/insights'
    | '/projections'
    | '/revenue'
    | '/staff-school'
    | '/training'
    | '/validation'
    | '/admin/forgot'
    | '/admin/login'
    | '/admin/reset'
    | '/performance/$kra'
    | '/admin'
    | '/performance'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/bk'
    | '/detailed'
    | '/executive-deck'
    | '/insights'
    | '/projections'
    | '/revenue'
    | '/staff-school'
    | '/training'
    | '/validation'
    | '/admin/forgot'
    | '/admin/login'
    | '/admin/reset'
    | '/performance/$kra'
    | '/admin/'
    | '/performance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  BkRoute: typeof BkRoute
  DetailedRoute: typeof DetailedRoute
  ExecutiveDeckRoute: typeof ExecutiveDeckRoute
  InsightsRoute: typeof InsightsRoute
  ProjectionsRoute: typeof ProjectionsRoute
  RevenueRoute: typeof RevenueRoute
  StaffSchoolRoute: typeof StaffSchoolRoute
  TrainingRoute: typeof TrainingRoute
  ValidationRoute: typeof ValidationRoute
  PerformanceKraRoute: typeof PerformanceKraRoute
  PerformanceIndexRoute: typeof PerformanceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-school': {
      id: '/staff-school'
      path: '/staff-school'
      fullPath: '/staff-school'
      preLoaderRoute: typeof StaffSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projections': {
      id: '/projections'
      path: '/projections'
      fullPath: '/projections'
      preLoaderRoute: typeof ProjectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-deck': {
      id: '/executive-deck'
      path: '/executive-deck'
      fullPath: '/executive-deck'
      preLoaderRoute: typeof ExecutiveDeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detailed': {
      id: '/detailed'
      path: '/detailed'
      fullPath: '/detailed'
      preLoaderRoute: typeof DetailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bk': {
      id: '/bk'
      path: '/bk'
      fullPath: '/bk'
      preLoaderRoute: typeof BkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance/': {
      id: '/performance/'
      path: '/performance'
      fullPath: '/performance/'
      preLoaderRoute: typeof PerformanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/performance/$kra': {
      id: '/performance/$kra'
      path: '/performance/$kra'
      fullPath: '/performance/$kra'
      preLoaderRoute: typeof PerformanceKraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset': {
      id: '/admin/reset'
      path: '/reset'
      fullPath: '/admin/reset'
      preLoaderRoute: typeof AdminResetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forgot': {
      id: '/admin/forgot'
      path: '/forgot'
      fullPath: '/admin/forgot'
      preLoaderRoute: typeof AdminForgotRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminForgotRoute: typeof AdminForgotRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetRoute: typeof AdminResetRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminForgotRoute: AdminForgotRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminResetRoute: AdminResetRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  BkRoute: BkRoute,
  DetailedRoute: DetailedRoute,
  ExecutiveDeckRoute: ExecutiveDeckRoute,
  InsightsRoute: InsightsRoute,
  ProjectionsRoute: ProjectionsRoute,
  RevenueRoute: RevenueRoute,
  StaffSchoolRoute: StaffSchoolRoute,
  TrainingRoute: TrainingRoute,
  ValidationRoute: ValidationRoute,
  PerformanceKraRoute: PerformanceKraRoute,
  PerformanceIndexRoute: PerformanceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
